# Brain MRI (magnetic resonance imaging) segmentation


## The task

This project addresses the segmentation of FLAIR abnormalities in brain MR images. Each image in the dataset is paired with a manually created FLAIR abnormality segmentation mask, so the goal is to segment the abnormal (tumor) region in lower-grade glioma cases.

Source kaggle challenge: https://www.kaggle.com/datasets/mateuszbuda/lgg-mri-segmentation/data

## Notebook structure:
- 1. Dataset

In [9]:
import kagglehub
from glob import glob
import cv2
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
TRAIN_SPLIT = 0.7
TEST_SPLIT = 0.5

RANDOM_STATE = 42

## **1. The dataset**

The **LGG Segmentation Dataset** contains brain MR images together with manual FLAIR abnormality segmentation masks. The images were obtained from *The Cancer Imaging Archive* (TCIA) and correspond to **110 patients** included in *The Cancer Genome Atlas* (TCGA) lower-grade glioma collection, each having at least a fluid-attenuated inversion recovery (FLAIR) sequence and genomic cluster data available.

Tumor genomic clusters and patient data are provided in the `data.csv` file. For more information on the genomic data, refer to the publication *"Comprehensive, Integrative Genomic Analysis of Diffuse Lower-Grade Gliomas"* and its supplementary material: https://www.nejm.org/doi/full/10.1056/NEJMoa1402121

In [2]:
# Download latest version
path = kagglehub.dataset_download("mateuszbuda/lgg-mri-segmentation")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/mateuszbuda/lgg-mri-segmentation

In [7]:
mask_paths = glob("/kaggle/input/**/*mask*.*", recursive=True)

print("Number of masks:", len(mask_paths))

for i,path in enumerate(mask_paths[:3]):
    print(f"{i}° path: {path}")

Number of masks: 7858
0° path: /kaggle/input/datasets/mateuszbuda/lgg-mri-segmentation/kaggle_3m/TCGA_DU_7010_19860307/TCGA_DU_7010_19860307_56_mask.tif
1° path: /kaggle/input/datasets/mateuszbuda/lgg-mri-segmentation/kaggle_3m/TCGA_DU_7010_19860307/TCGA_DU_7010_19860307_8_mask.tif
2° path: /kaggle/input/datasets/mateuszbuda/lgg-mri-segmentation/kaggle_3m/TCGA_DU_7010_19860307/TCGA_DU_7010_19860307_34_mask.tif

Every directory inside the dataset contains pairs of images:
- name_img.tif
- name_img_mask.tif

In [10]:
images_paths = []

for i in masks_paths:
    images_paths.append(i.replace('_mask', ''))

df = pd.DataFrame(data= {'images_paths': images_paths, 'masks_paths': masks_paths})

15716

In [12]:
df.head()

,images_paths,masks_paths
0,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...
1,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...
2,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...
3,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...
4,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...

In [14]:
df.describe()

,images_paths,masks_paths
count,7858,7858
unique,7858,7858
top,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...,/kaggle/input/datasets/mateuszbuda/lgg-mri-seg...
freq,1,1

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7858 entries, 0 to 7857
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   images_paths  7858 non-null   object
 1   masks_paths   7858 non-null   object
dtypes: object(2)
memory usage: 122.9+ KB

In [ ]:
# create training dataframe
train_df, val_test_df = train_test_split(df, random_state = RANDOM_STATE, train_size= TRAINING_SPLIT)

# create validation and test dataframe
val_df, test_df = train_test_split(val_test_df, train_size= TEST_SPLIT)

## References

This dataset is used in:

- Mateusz Buda, Ashirbani Saha, Maciej A. Mazurowski. *"Association of genomic subtypes of lower-grade gliomas with shape features automatically extracted by a deep learning algorithm."* Computers in Biology and Medicine, 2019.
- Maciej A. Mazurowski, Kal Clark, Nicholas M. Czarnek, Parisa Shamsesfandabadi, Katherine B. Peters, Ashirbani Saha. *"Radiogenomics of lower-grade glioma: algorithmically-assessed tumor shape is associated with tumor genomic subtypes and patient outcomes in a multi-institutional study with The Cancer Genome Atlas data."* Journal of Neuro-Oncology, 2017.